# Generated by Django 4.2.13 on 2024-06-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("no_of_pages", models.IntegerField()),
                ("publish_date", models.DateField()),
                ("quantity", models.IntegerField()),
            ],
        ),
    ]
